language: common-lisp
sudo: required
# Needed for cross-compiling libsecp256k1 for 32-bit lisp
# implementations.
addons:
  apt:
    packages:
      - gcc-multilib
env:
  matrix:
    - LISP=abcl
    - LISP=allegro LISP32=1
    - LISP=sbcl
    - LISP=sbcl32  LISP32=1
    - LISP=ccl
    - LISP=ccl32   LISP32=1
    - LISP=clisp
    - LISP=clisp32 LISP32=1
    - LISP=ecl

matrix:
  allow_failures:
    - env: LISP=allegro LISP32=1
    - env: LISP=clisp
    - env: LISP=clisp32 LISP32=1
    - env: LISP=ecl
    - env: LISP=ccl32   LISP32=1

install:
  # Install libsecp256k1.
  - git clone https://github.com/bitcoin-core/secp256k1
  - cd secp256k1 && ./autogen.sh
  - if [ -n "$LISP32" ]; then export USE_HOST="--host=i686-linux-gnu"; fi
  - if [ -n "$LISP32" ]; then export CFLAGS="-m32"; fi
  - ./configure $USE_HOST "CFLAGS=$CFLAGS" && make && sudo make install
  # Make sure CFFI can find the library.
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  # Install Lisp CI environment.
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh

script:
  # Ensure we enter a debugger on error/failure and immediately call
  # UIOP:QUIT.
  - cl -l fiveam
       -e '(setf fiveam:*debug-on-error* t)'
       -e '(setf fiveam:*debug-on-failure* t)'
       -e '(setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore c h))
                   (uiop:quit -1)))'
       -e '(ql:quickload :bp/tests)'
